"""
Outfit model for garment combinations.
"""
import uuid
from typing import TYPE_CHECKING

from sqlalchemy import Column, DateTime, Float, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from backend.app.db.base import Base

if TYPE_CHECKING:
    from backend.app.models.user import User  # noqa: F401
    from backend.app.models.outfit_feedback import OutfitFeedback  # noqa: F401


class Outfit(Base):
    """
    Outfit model representing a combination of garments.
    
    Source values:
    - recommended: Generated by recommendation system
    - user_created: Created manually by user
    - worn: User marked as worn
    
    Context JSONB structure:
    {
        "weather": {"temp": "cool", "conditions": ["rainy"]},
        "formality": "smart_casual",
        "constraints_applied": {...}
    }
    """

    __tablename__ = "outfits"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)

    # Garments in this outfit (array of UUIDs)
    garment_ids = Column(ARRAY(UUID(as_uuid=True)), nullable=False)

    # Context
    occasion = Column(String(50), nullable=True)
    # Values: casual, work, date, party, interview, wedding, workout, etc.
    context = Column(JSONB, nullable=True)

    # Scoring
    compatibility_score = Column(Float, nullable=True)
    score_breakdown = Column(JSONB, nullable=True)
    explanation = Column(Text, nullable=True)

    # Source
    source = Column(String(20), nullable=False)
    # Values: recommended, user_created, worn

    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), nullable=False)

    # Relationships
    user = relationship("User", back_populates="outfits")
    feedback = relationship("OutfitFeedback", back_populates="outfit", cascade="all, delete-orphan")

    # Indexes
    __table_args__ = (
        Index("idx_outfits_user", "user_id"),
        Index("idx_outfits_occasion", "occasion"),
    )

    def __repr__(self) -> str:
        return f"<Outfit(id={self.id}, user_id={self.user_id}, source={self.source})>"
